export const GET_INFLUENCER_LODING = 'GET_INFLUENCER_LODING';
export const GET_INFLUENCER_SUCCESS = 'GET_ INFLUENCER_SUCESS';
export const GET_INFLUENCER_FAILED = 'GET_INFLUENCER_FAILED';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT'; 

export const ADD_INFLUENCER_FAILED = 'GET_INFLUENCER_FAILED';



export const GET_INFLUENCERI_LODING = 'GET_INFLUENCERI_LODING';
export const GET_INFLUENCERI_SUCCESS = 'GET_ INFLUENCERI_SUCESS';
export const GET_INFLUENCERI_FAILED = 'GET_INFLUENCERI_FAILED';


export const DELETE_INFLUENCER_SUCCESS = 'DELETE_INFLUENCER_SUCESS';
export const DELETE_INFLUENCER_FAILED = 'DELETE_INFLUENCER_FAILED';

export const UPDATE_INFLUENCER_SUCCESS = 'UPDATE_INFLUENCER_SUCESS';
export const UPDATE_INFLUENCER_FAILED = 'UPDATE_INFLUENCER_FAILED';