
// customer action
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
 
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT'; 

export const GET_CUSTOMER_LODING = 'GET_CUSTOMER_LODING';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCESS';
export const GET_CUSTOMER_FAILED = 'GET_CUSTOMER_FAILED';

export const DELETE_CUSTOMER_SUCCESS = 'DELETE_USER_SUCESS';
export const DELETE_CUSTOMER_FAILED = 'DELETE_USER_FAILED';

export const UPFATE_CUSTOMER_SUCCESS = 'DELETE_USER_SUCESS';
export const UPDATE_CUSTOMER_FAILED = 'DELETE_USER_FAILED';